from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, PageBreak
from reportlab.lib import colors
from io import BytesIO
from datetime import datetime

class OwnershipReportGenerator:
    @staticmethod
    def generate_pdf(project_name: str, jurisdiction: str, ownership_data: dict) -> BytesIO:
        buffer = BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=letter, topMargin=0.5*inch, bottomMargin=0.5*inch)

        styles = getSampleStyleSheet()
        title_style = ParagraphStyle(
            'CustomTitle',
            parent=styles['Heading1'],
            fontSize=18,
            textColor=colors.HexColor('#1a1a1a'),
            spaceAfter=12,
        )

        heading_style = ParagraphStyle(
            'CustomHeading',
            parent=styles['Heading2'],
            fontSize=12,
            textColor=colors.HexColor('#333333'),
            spaceAfter=8,
        )

        story = []

        # Title Page
        story.append(Paragraph(f"OWNERSHIP REPORT", title_style))
        story.append(Spacer(1, 0.2*inch))
        story.append(Paragraph(f"<b>Project:</b> {project_name}", styles['Normal']))
        story.append(Paragraph(f"<b>Jurisdiction:</b> {jurisdiction}", styles['Normal']))
        story.append(Paragraph(f"<b>Report Date:</b> {datetime.now().strftime('%B %d, %Y')}", styles['Normal']))
        story.append(Spacer(1, 0.3*inch))

        # Ownership Table
        story.append(Paragraph("FRACTIONAL OWNERSHIP SUMMARY", heading_style))

        owners = ownership_data.get('owners', [])
        table_data = [['Party Name', 'Fraction', 'Percentage', 'Mineral Estate', 'Burdens']]

        for owner in owners:
            table_data.append([
                owner.get('name', ''),
                owner.get('fraction', ''),
                f"{owner.get('percentage', 0)}%",
                owner.get('mineral_estate', ''),
                owner.get('burdens', 'None')
            ])

        table = Table(table_data, colWidths=[2*inch, 1*inch, 1*inch, 1.5*inch, 1.5*inch])
        table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#2c3e50')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 10),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
            ('GRID', (0, 0), (-1, -1), 1, colors.black),
            ('FONTNAME', (0, 1), (-1, -1), 'Helvetica'),
            ('FONTSIZE', (0, 1), (-1, -1), 9),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#f5f5f5')]),
        ]))

        story.append(table)
        story.append(Spacer(1, 0.3*inch))

        # Summary Stats
        story.append(Paragraph("ACREAGE SUMMARY", heading_style))
        total_acres = ownership_data.get('total_acres', 0)
        leased = ownership_data.get('leased_acres', 0)
        open_acres = ownership_data.get('open_acres', 0)

        summary_data = [
            ['Total Acres', str(total_acres)],
            ['Leased Acres', str(leased)],
            ['Open Acres', str(open_acres)],
        ]

        summary_table = Table(summary_data, colWidths=[3*inch, 2*inch])
        summary_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor('#ecf0f1')),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, -1), 'Helvetica'),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('GRID', (0, 0), (-1, -1), 1, colors.grey),
        ]))

        story.append(summary_table)
        story.append(Spacer(1, 0.2*inch))

        # Footer
        story.append(Spacer(1, 0.5*inch))
        story.append(Paragraph(
            "<i>This report was generated by Section - Land Graph Operating Layer.</i>",
            styles['Normal']
        ))

        doc.build(story)
        buffer.seek(0)
        return buffer
